import { Lexend} from 'next/font/google'
import './globals.css'
import Navbar from './Navbar/Navbar'

const lex = Lexend({ subsets: ['latin'] })

export const metadata = {
  title: 'Macarena Epifani',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lex.className}>
        {children}</body>
    </html>
  )
}
